### ISSUE TITLE
definition of issues

### ISSUE THREAD

**Issue by jwp23** [joelparkerhenderson/issues#1]
In this context, does Issues refer to incidents that would trigger postmortem or is it Issues as in a ticket in JIRA? The medical charting paradigm works well for user stories as well if the terminology were changed.

**Comment by joelparkerhenderson** [comment]
Thanks for the question!

For our teams the word "issue" is a generic catch all that includes for example:

* A bug report
* A ticket in a tracking tool
* A task in a to-do list
* A use case in a project plan
* A user email that we want to handle
* A feedback comment that we want to handle
* Etc.

I will add this to the README now.

**Comment by jwp23** [comment]
Thanks for the answer and the update to the README. I'll continue to experiment with the medical charting paradigm for my team's board.
